namespace ServiceMultiProcess
{
    partial class ClassMP
    {
        /// <summary> 
        /// Variable required for designer.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean-up used resources
        /// </summary>
        /// <param name="disposing">true if the managed resources must be deleted; otherwise, false</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by Component Designer

        /// <summary> 
        /// Method required for designer support - do not modify         
        /// </summary>
        private void InitializeComponent()
        {
            this.ServiceName = "Service Multi Process";
        }

        #endregion

    }
}
